# ==============================================================================
# Deasy - Windows Runner CI/CD Matrix
# ==============================================================================

stages:
  - test
  - build

default:
  tags:
    - windows
    - powershell

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

lint_and_build:
  stage: test
  script:
    - npm install
    - npm run build
